version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    command: 'python main.py'
    ports:
      - 5000:5000
    volumes:
      - .:/app
    depends_on:
      - db

  queue:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    command: 'python consumer.py'
    depends_on:
      - db

  db:
    image: mysql:5.7.22
    restart: always
    ports:
      - 33067:3306
    volumes:
      - .dbdata:/var/lib/mysql
    environment:
      MYSQL_DATABASE: main
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root

